apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    targetPort: 80
    nodePort: {{ .Values.service.web.nodePort }}
    protocol: TCP
    name: web
  - port: 53
    targetPort: 53
    nodePort: {{ .Values.service.dns.nodePort }}
    protocol: UDP
    name: dns-udp
  - port: 53
    targetPort: 53
    nodePort: {{ .Values.service.dns.nodePort }}
    protocol: TCP
    name: dns-tcp
  selector:
    app: pihole
