server:
  serviceType: NodePort
  httpNodePort: 30080
  httpsNodePort: 30443
  ingress:
    enabled: true
  configs:
    params:
      server.insecure: true
redis:
  passwordSecret:
    name: argocd-redis-secret
    key: password

