apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-usb-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  # Example size, replace with actual size