prometheus:
  alertmanager:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  configmapReload:
    prometheus:
      enabled: false
  server:
    nodeSelector:
      kubernetes.io/hostname: node-0
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      runAsGroup: 1000
      fsGroup: 1000
    tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
    persistentVolume:
      enabled: true
      existingClaim: "prometheus-usb-pvc"
      volumeName: "prometheus-usb-pv"
    service:
      port: 9090