image:
  repository: pihole/pihole
  tag: "latest"

service:
  type: NodePort
  externalTrafficPolicy: Cluster
  web:
    port: 80
    nodePort: 30123
  dns:
    port: 53
    nodePort: 30054

persistence:
  enabled: true
  size: 2Gi

resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "200m"

adminPassword: "bmFraW5hMTENCg=="

# # Add the upstream DNS configuration for Pi-hole
# piHole:
#   upstreamServers:
#     # Use the service name of the Unbound deployment. 
#     # This assumes Unbound is deployed in the same namespace as Pi-hole.
#     - "unbound.unbound.svc.cluster.local#53"
