apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-usb-pv
  labels:
    type: local
spec:
  storageClassName: pihole-manual
  capacity:
    storage: 1.85Gi  # Example size, replace with actual size
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/usb2"