apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: prometheus-usb-pv  # Reference the existing PV by name

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq-pvc
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  volumeName: prometheus-usb-pv  # Reference the existing PV by name
