apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq-pvc
  labels:
    app: pihole
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
