apiVersion: v1
kind: ConfigMap
metadata:
  name: unbound-config
data:
  unbound.conf: |
    server:
      interface: 0.0.0.0
      access-control: 0.0.0.0/0 allow
      port: 53
      do-ip6: no
      do-udp: yes
      do-tcp: yes
      root-hints: "/etc/unbound/root.hints"
      hide-identity: yes
      hide-version: yes
      num-threads: 2
      verbosity: 1
      # Uncomment the following if you want to specify the number of outgoing DNS connections
      # num-queries-per-thread: 4096
      # max-udp-size: 4096
      
    # Zone for forwarding
    forward-zone:
      name: "."
      forward-addr: 1.1.1.1  # Cloudflare DNS
      forward-addr: 8.8.8.8  # Google DNS

  root.hints: |
    . 3600 IN NS a.root-servers.net.
    a.root-servers.net. 3600 IN A 198.41.0.4
    a.root-servers.net. 3600 IN AAAA 2001:503:ba3e::2:30

    . 3600 IN NS b.root-servers.net.
    b.root-servers.net. 3600 IN A 199.9.14.201
    b.root-servers.net. 3600 IN AAAA 2001:500:200::b

    . 3600 IN NS c.root-servers.net.
    c.root-servers.net. 3600 IN A 192.33.4.12
    c.root-servers.net. 3600 IN AAAA 2001:500:2::c

    . 3600 IN NS d.root-servers.net.
    d.root-servers.net. 3600 IN A 203.119.24.34
    d.root-servers.net. 3600 IN AAAA 2001:500:2d::d

    . 3600 IN NS e.root-servers.net.
    e.root-servers.net. 3600 IN A 192.203.230.10
    e.root-servers.net. 3600 IN AAAA 2001:500:a8::e

    . 3600 IN NS f.root-servers.net.
    f.root-servers.net. 3600 IN A 192.5.5.241
    f.root-servers.net. 3600 IN AAAA 2001:500:2f::f

    . 3600 IN NS g.root-servers.net.
    g.root-servers.net. 3600 IN A 192.112.36.4
    g.root-servers.net. 3600 IN AAAA 2001:500:12::d0

    . 3600 IN NS h.root-servers.net.
    h.root-servers.net. 3600 IN A 198.97.190.53
    h.root-servers.net. 3600 IN AAAA 2001:500:1::803f:235

    . 3600 IN NS i.root-servers.net.
    i.root-servers.net. 3600 IN A 192.36.148.17
    i.root-servers.net. 3600 IN AAAA 2001:7fe::53

    . 3600 IN NS j.root-servers.net.
    j.root-servers.net. 3600 IN A 192.58.128.30
    j.root-servers.net. 3600 IN AAAA 2001:503:c27::2:30

    . 3600 IN NS k.root-servers.net.
    k.root-servers.net. 3600 IN A 193.0.14.129
    k.root-servers.net. 3600 IN AAAA 2001:7fd::1

    . 3600 IN NS l.root-servers.net.
    l.root-servers.net. 3600 IN A 199.7.83.42
    l.root-servers.net. 3600 IN AAAA 2001:500:1::803f:15

    . 3600 IN NS m.root-servers.net.
    m.root-servers.net. 3600 IN A 202.12.27.33
    m.root-servers.net. 3600 IN AAAA 2001:dc3::35
