apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: mvance/unbound:latest
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: /etc/unbound/unbound.conf
              subPath: unbound.conf
            - name: config-volume
              mountPath: /etc/unbound/root.hints
              subPath: root.hints
      volumes:
        - name: config-volume
          configMap:
            name: unbound-config

apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: dns-services
spec:
  ports:
    - name: udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: tcp
      port: 53
      targetPort: 53
      protocol: TCP
  selector:
    app: unbound