apiVersion: v1
kind: Service
metadata:
  name: {{ include "unbound.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 53
      protocol: UDP
  selector:
    app: {{ include "unbound.name" . }}
  type: {{ .Values.service.type }}
